apiVersion: http.crossplane.io/v1alpha2
kind: NamespacedDisposableRequest
metadata:
  name: example-namespaced-disposable-request
  namespace: default
spec:
  forProvider:
    url: "https://httpbin.org/post"
    method: "POST"
    body: '{"test": "data"}'
    headers:
      Content-Type: ["application/json"]
  providerConfigRef:
    kind: ProviderConfig
    name: http-conf